image: maven:3.9-eclipse-temurin-17

stages:
  - build
  - unit_test
  - integration_test

build:
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

unit_test:
  stage: unit_test
  script:
    - mvn test -Dtest=org.openapitools.testng.CalculatorTest
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
    reports:
      junit:
        - target/surefire-reports/junitreports/*.xml
    expire_in: 1 week

integration_test:
  stage: integration_test
  script:
    - mvn test -Dtest=TestSuite
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
    reports:
      junit:
        - target/surefire-reports/junitreports/*.xml
    expire_in: 1 week